#!/usr/bin/env bash
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "HELLO! This takes a path argument and starts batch-transcode-video with Mark's preferred settings."
echo "========================="

if [ "$#" -ne 1 ]; then
    printf "${RED}FAILED${NC}\n"
    printf "${RED}This takes a single path. If there are spaces in your path, escape them or put quotes around it.${NC}\n"
    exit
fi

printf "${GREEN}SENDING TO BATCH${NC}\n"
echo "========================="

VIDEOPATH=${1?Error: no path to folder containing videos}


# Old Version
# batch-transcode-video --input "$VIDEOPATH/" --output "$VIDEOPATH Plex/"  --force 1 -- --add-audio all --add-subtitle all --force-subtitle scan

# New version with Detelecine/Deinterlace
batch-transcode-video --input "${VIDEOPATH}/" --output "${VIDEOPATH}Plex/"  --force 1 -- --add-audio all --add-subtitle all --force-subtitle scan --handbrake-option detelecine --handbrake-option comb-detect --handbrake-option decomb


echo "========================="
printf "${YELLOW}FINISHED${NC}\n"
echo "========================="
